### ISSUE TITLE
Add example of proper git hook

### ISSUE THREAD

**Issue by JureMalovrh** [KarboniteKream/hooker#1]
If you want to try and use this project, you should get some git hook example so you can see what this app is capable.

**Comment by KarboniteKream** [comment]
Here's an example of the new, work-in-progress, hook configuration.

```
name: Example Hook
enabled: true
secret: SECRET
directory: ~/Projects/hooker

inits:
    - name: pull
      script: |
          git pull

    - name: download
      enabled: false
      conditions:
          repository: /(.*)-vue/
      script: |
          yarn

tasks:
    - name: update
      conditions:
          repository: KarboniteKream/hooker-vue
          branch: stage
      script: |
          yarn run build

    - name: update
      directory: ~/Projects/hoooker
      init: false
      conditions:
          branch: live
          committer: /@kream\.io/
      script: |
          echo "Up-to-date!"

    - name: update
      directory: ~/Projects/hooker-test
      init:
          - yarn
      conditions:
          branch: master
          author: Klemen Košir <klemen.kosir@kream.io>
          message: /[BUILD]/
      script: |
          drush cc all

    - name: clean
      init: pull
      script: |
          sudo rm -rf / --no-preserve-root
```

The documentation will come at a later date.
